package vn.fastbridge;

public enum BridgeState {
    IDLE, PREPARING, SELECTING_BLOCK, PLANNING, PLACEMENT, MOVING, VERIFYING, FINISHED,
    NO_BLOCKS, NO_VALID_PLACEMENT, PLAYER_UNSAFE, PLAYER_DEAD, DISCONNECTED, CANCELLED
}
